---
# What config to enable/disable

## Set SSH key copy if it is not part of your other provisioning
install_ssh_key: true
## Setup Java if it is not part of your other provisioning
install_openjdk: true

## TODO: Cater for Confluent Platform of Zookeeper and Kafka
## This naming convention can change
install_zookeeper_opensource: true
install_kafka_opensource: true
## Configure Topics
configure_topics: true
## Setup Authentication and Access Controls
configure_sasl: true
configure_acl: true


# Some Kafka default config variables
kafka_path: /opt/kafka
kafka_user: kafka
kafka_group: kafka
kafka_auto_create_topics_enable: false
kafka_partition_count: 3
kafka_replication_count: 2

# Kafka SASL specific variables
kafka_opts:
  -Djava.security.auth.login.config=/opt/kafka/config/jaas.conf
kafka_listener_protocol: SASL_PLAINTEXT
kafka_inter_broker_listener_protocol: SASL_PLAINTEXT
kafka_sasl_mechanism_inter_broker_protocol: PLAIN
kafka_sasl_enabled_mechanisms: PLAIN
kafka_super_users: "User:admin"  #SASL Admin User that has access to administor kafka.
kafka_allow_everyone_if_no_acl_found: 'false' 
kafka_authorizer_class_name: "kafka.security.authorizer.AclAuthorizer" # This has changed as of version 2.5 or 2.6 should be authorizer kafka.security.authorizer.AclAuthorizer

topics_acl_users:
#### This sequence needs to be repeated for every topic ####
- topic: metricbeat # The topic name that you want the Consumer and Producer groups to have ACL's on.
  consumers:
  - group: metricebeatCon1
    username: user1
  - group: metricebeatCon2
    username: user2
  producers:
  # NOTE: Can have more than 1 username but cannot have wildcard and usernames.
  # - '*'   # Allows all authenticated users to write to a topic
  - user1 # Specific user has access to a topic. Should match a user in the JAAS.CONF file.
  - user2
 
############################################################
## TODO: Setup plays to include more than one authoriser and more than one port and client type
## TODO: Build and refine plays to include below logic steps.
# configure_kafka: false
# configure_ssl: false
# configure_plaintext: false
# install_zookeeper_confluent: false
# install_kafka_confluent: false