- name: kafka
  src: https://github.com/digitalis-io/ansible-kafka.git
  version: master
- name: zookeeper
  src: https://github.com/digitalis-io/ansible-zookeeper.git
  version: master
- name: openjdk
  src: https://github.com/digitalis-io/ansible-role-java.git
  version: master