---
- name: get list of all topics created on kafka
  command: "{{ kafka_path }}/bin/kafka-topics.sh --zookeeper {{ kafka_zookeeper_connect }} --list"
  register: topiclist

# - name: Display the list of existing topics on the output
#   debug: var=topiclist

- name: create all topics
  command: "{{ kafka_path }}/bin/kafka-topics.sh --create --zookeeper {{ kafka_zookeeper_connect }} --replication-factor {{ kafka_replication_count }} --partitions {{ kafka_partition_count }} --topic {{ item.topic }}"
  loop: "{{ topics_acl_users }}"
  when: 'item.topic not in topiclist.stdout'

- name: Pause topic creation for 2 seconds between topic create commands
  pause: 
    seconds: 2
