- name: Verify
  hosts: all

  tasks:
    - name: Get users
      getent:
        database: passwd

    - name: Get groups
      getent:
        database: group

    - name: Assert that user and group 'kafka' exists
      assert:
        that:
          - "'kafka' in getent_passwd"
          - "'kafka' in getent_group"

    - name: Register '/opt/kafka_2.13-2.7.0' installation directory status
      stat:
        path: '/opt/kafka_2.13-2.7.0'
      register: install_dir

    - name: Assert that '/opt/kafka_2.13-2.7.0' directory is created
      assert:
        that:
          - install_dir.stat.exists
          - install_dir.stat.isdir
          - install_dir.stat.pw_name == 'kafka'
          - install_dir.stat.gr_name == 'kafka'

    - name: Register '/opt/kafka' symlink directory status
      stat:
        path: '/opt/kafka'
      register: kafka_dir

    - name: Assert that '/opt/kafka' symlink is created
      assert:
        that:
          - kafka_dir.stat.exists
          - kafka_dir.stat.islnk
          - kafka_dir.stat.lnk_target == '/opt/kafka_2.13-2.7.0'

    - name: Register '/etc/kafka' directory status
      stat:
        path: '/etc/kafka'
      register: config_dir

    - name: Assert that '/etc/kafka' directory is created
      assert:
        that:
          - config_dir.stat.exists
          - config_dir.stat.isdir
          - config_dir.stat.pw_name == 'kafka'
          - config_dir.stat.gr_name == 'kafka'

    - name: Populate service facts
      service_facts:

    - name: Assert that Kafka service is installed, running, and enabled
      assert:
        that:
          - "'kafka.service' in ansible_facts.services"
          - ansible_facts.services['kafka.service'].state == 'running'
          - ansible_facts.services['kafka.service'].status == 'enabled'
