---
- name: update ACL write access for producers
  become: true
  block:
  - name: execute command
    shell: 
      "{{ kafka_path }}/bin/kafka-acls.sh --authorizer kafka.security.auth.SimpleAclAuthorizer --authorizer-properties zookeeper.connect={{ kafka_zookeeper_connect }} --add --allow-principal User:{{ item.1 }}  --producer --topic {{ item.0.topic }}; sleep 3"
    loop: "{{ topics_acl_users|subelements('producers') }}"
    when: item.0

  - name: update ACL read access for consumers
    shell: "{{ kafka_path }}/bin/kafka-acls.sh --authorizer kafka.security.auth.SimpleAclAuthorizer --authorizer-properties zookeeper.connect={{ kafka_zookeeper_connect }} --add --allow-principal User:{{ item.1.username }} --consumer --topic {{ item.0.topic }} --group {{ item.1.group }}; sleep 1"
    loop: "{{ topics_acl_users|subelements('consumers') }}"
    when: item.0
