---
galaxy_info:
  author: Simon Leigh
  description: Apache ZooKeeper installation for RHEL/CentOS and Debian/Ubuntu
  license: MIT
  min_ansible_version: 2.10.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - zookeeper
    - clustering

dependencies: []
