---
# Update the Jaas.conf file with the new users. If the users are different it should then restart the containers to
# apply the new changes.

- name: update jaas.conf file
  become: true
  template:
    src: ./templates/jaas.j2
    dest: "{{ kafka_path }}/config/jaas.conf"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 'u=rw,g=r,o='
  notify: "restart kafka"


- name: create Client Config File
  become: true
  template:
    src: ./templates/kafkaclient.jaas.j2
    dest: "{{ kafka_path }}/config/kafkaclient.jaas.conf"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 'u=r,g=r,o=r'