---
- name: Set authorized key from file
  hosts: all
  serial: "{{ serial_override | default(1) }}"
  become: true
  vars_files:
    - "../group_vars/all.yml"
  tasks:
    - name: Copy ssh key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      when: install_ssh_key

- name: Install OpenJDK
  hosts: all
  serial: "{{ serial_override | default(1) }}"
  become: true
  vars_files:
    - "../group_vars/all.yml"
  tasks:  
  - name: Update Package Manager Caches
    yum:
      update_cache: yes
    when: ansible_distribution == 'CentOS' or
          ansible_distribution == 'Red Hat Enterprise Linux' or
          ansible_distribution == 'RedHat' or
          ansible_distribution == 'Fedora'
  
  - name: Update Package Manager Caches
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu' or ansible_os_family == 'Debian'
  
  - name: Install openjdk
    include_role:
      name: openjdk
    when: install_openjdk